In [1]:
import os
import pandas as pd
from natsort import natsorted
import re
import numpy as np

sub-10059 has 3 acqs of denoised tedana
sub-10108 has 3 acqs of denoised tedana
sub-10234 has 3 acqs of denoised tedana
sub-10125 has 3 acqs of denoised tedana
sub-10017 has 3 acqs of denoised tedana
sub-10094 has 3 acqs of denoised tedana
sub-10137 has 3 acqs of denoised tedana
sub-10154 has 3 acqs of denoised tedana
sub-10130 has 3 acqs of denoised tedana
sub-10221 has 3 acqs of denoised tedana
sub-12042 has 3 acqs of denoised tedana
sub-10085 has 3 acqs of denoised tedana
sub-10303 has 1 acqs of denoised tedana
sub-10035 has 6 acqs of denoised tedana
sub-10186 has 3 acqs of denoised tedana
sub-10142 has 3 acqs of denoised tedana
sub-10043 has 3 acqs of denoised tedana
sub-10035retest has 3 acqs of denoised tedana
sub-10188 has 3 acqs of denoised tedana
sub-10074 has 3 acqs of denoised tedana
sub-10080 has 3 acqs of denoised tedana
sub-10041 has 3 acqs of denoised tedana
sub-10150 has 3 acqs of denoised tedana
sub-10078 has 3 acqs of denoised tedana
sub-10069 has 3 acqs of denoised tedana
sub-10024 has 3 acqs of denoised tedana
sub-10136 has 3 acqs of denoised tedana
sub-10198 has 3 acqs of denoised tedana
sub-10203 has 3 acqs of denoised tedana
sub-10054 has 3 acqs of denoised tedana
sub-10223 has 2 acqs of denoised tedana
fmriprep failed for sub-10198 mb1me4
fmriprep failed for sub-10198 mb3me4
fmriprep failed for sub-10198 mb6me4

,cosine00,cosine01,cosine02,cosine03,cosine04,non_steady_state_outlier00,trans_x,trans_y,trans_z,rot_x,rot_y,rot_z,framewise_displacement,ICA_00,ICA_01,ICA_06,ICA_08,ICA_09,ICA_11,ICA_15
0,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.034475,-0.061768,0.031454,-0.001201,0.001458,1.546950e-04,NaN,-1.525806,1.131811,-1.215310,-1.835926,-0.295578,-1.729271,-0.157424
1,0.146626,0.146563,0.146459,0.146313,0.146124,0.0,0.041448,-0.061729,0.021357,-0.000834,0.001999,1.704320e-04,0.063298,-1.860169,-0.885044,0.250613,-2.758759,1.990669,-1.732917,1.493973
2,0.146459,0.145895,0.144956,0.143645,0.141966,0.0,0.016056,-0.045082,0.011158,-0.001551,0.002445,4.235160e-22,0.118940,-0.938841,1.173763,-1.551220,-2.424261,-1.737960,-1.033008,0.122783
3,0.146124,0.144560,0.141966,0.138359,0.133767,0.0,0.017021,-0.037165,-0.002373,-0.001029,0.002298,0.000000e+00,0.055889,-1.223100,-0.122734,-1.353424,0.107808,1.049349,-1.842123,1.080127
4,0.145623,0.142566,0.137519,0.130551,0.121760,0.0,-0.020870,-0.061728,-0.070496,-0.001193,0.001882,-6.455850e-04,0.191846,-1.768755,-0.819070,-1.922677,-1.806694,0.205668,-1.097188,1.054757
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,-0.144956,0.139922,-0.131660,0.120363,-0.106289,0.0,-0.123386,0.008669,-0.061302,0.002203,0.000790,-3.419300e-03,0.054993,1.127834,0.944462,0.760899,-0.155602,0.908920,0.486690,-2.550787
90,-0.145623,0.142566,-0.137519,0.130551,-0.121760,0.0,-0.118796,-0.007736,-0.047276,0.002469,0.000796,-3.419300e-03,0.048599,1.603145,-0.363146,1.621443,0.705284,-1.341748,1.260656,0.490195
91,-0.146124,0.144560,-0.141966,0.138359,-0.133767,0.0,-0.124174,0.007770,-0.046273,0.002086,0.000784,-3.843470e-03,0.062863,2.273978,-0.774093,-0.898011,1.260985,-0.324863,1.674872,-1.388009
92,-0.146459,0.145895,-0.144956,0.143645,-0.141966,0.0,-0.126287,-0.001870,-0.061310,0.002754,0.000719,-3.682660e-03,0.071514,1.720464,0.665026,1.621325,-0.673121,0.778666,0.340827,-1.439125
93,-0.146626,0.146563,-0.146459,0.146313,-0.146124,0.0,-0.116294,0.007670,-0.050844,0.002673,0.000942,-3.815060e-03,0.051832,1.037332,0.376953,1.214106,-1.198965,-0.196330,2.097472,-0.910067

In [71]:
fmriprep_confounds

,cosine00,cosine01,cosine02,cosine03,cosine04,non_steady_state_outlier00
0,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
1,0.146626,0.146563,0.146459,0.146313,0.146124,0.0
2,0.146459,0.145895,0.144956,0.143645,0.141966,0.0
3,0.146124,0.144560,0.141966,0.138359,0.133767,0.0
4,0.145623,0.142566,0.137519,0.130551,0.121760,0.0
...,...,...,...,...,...,...
89,-0.144956,0.139922,-0.131660,0.120363,-0.106289,0.0
90,-0.145623,0.142566,-0.137519,0.130551,-0.121760,0.0
91,-0.146124,0.144560,-0.141966,0.138359,-0.133767,0.0
92,-0.146459,0.145895,-0.144956,0.143645,-0.141966,0.0
93,-0.146626,0.146563,-0.146459,0.146313,-0.146124,0.0